"""empty message

Revision ID: 959833fa1e3d
Revises: 
Create Date: 2018-12-30 11:21:09.967390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '959833fa1e3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fitness', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('fitness', 'minutes',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               nullable=True)
    op.alter_column('fitness', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('fitness', 'who_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'fitness', 'typefit', ['type_id'], ['id'])
    op.create_foreign_key(None, 'fitness', 'fitwho', ['who_id'], ['id'])
    op.alter_column('fitstory', 'fit_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'fitstory', 'fitness', ['fit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fitstory', type_='foreignkey')
    op.alter_column('fitstory', 'fit_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'fitness', type_='foreignkey')
    op.drop_constraint(None, 'fitness', type_='foreignkey')
    op.alter_column('fitness', 'who_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('fitness', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('fitness', 'minutes',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               nullable=False)
    op.alter_column('fitness', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
